feat: commit-msg-hook: Add title format
Commit title format is below:

[category]: [ip_name]: [Title]

[category] can be one of followings
- feat : add new feature
- fix : fix bug
- doc : add documentation
- rename : rename file
- remove : remove file
- style : code style change (no affect on code)
- refactor : refactoring the code
- test : add test code for feature
- opt : optimization for performance
- script : script files

[ip_name] consists of alphabet(lowercase), numbers,
	 '-', and '_'
	 Must start with alphabet.

[Title] consists of alphabet, numbers, '-', '_',
	and spaces. Must start with uppercase.

Signed-off-by: Jaemin Choi <jaemin.jay@gmail.com>

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -11,5 +11,13 @@ if [ ${#commit_msg} -gt 50 ]; then
   exit 1
 fi
 
+regex="^(feat|fix|doc|rename|remove|style|refactor|test|opt|script): [a-z][-_a-z0-9]*: [A-Z][-A-Za-z0-9_ ]*$"
+
+if ! echo "$commit_msg" | grep -Eq "$regex"; then
+  echo "Commit title rule error."
+  exit 1
+fi
+
+
 #return success
 exit 0
